# Generated by Django 4.1 on 2022-08-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forthall_Gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='name',
            field=models.CharField(default=5, max_length=70),
            preserve_default=False,
        ),
    ]
